services:
  - type: web
    name: betty-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: ALLOWED_ORIGINS
        value: '["https://legendary-jelly-66624f.netlify.app"]'
      - key: FRONTEND_URL
        value: https://legendary-jelly-66624f.netlify.app
      - key: BACKEND_URL
        value: https://betty-predictor-1.onrender.com
      - key: TWA_APP_URL
        value: https://legendary-jelly-66624f.netlify.app
      - key: DATABASE_URL
        value: sqlite:///./betty.db
